Update build badge
pylhc/tfs pull request #52
Opened 2020-09-25 08:33 UTC by fsoubelet

Fix for #51

2020-09-25 14:00 UTC, fsoubelet commented
Will include fixes for #53 in here too

2020-09-25 15:05 UTC, fsoubelet commented
I got the docstrings up-to-date in ef39b65, and in a format that goes well with `sphinx`'s parsing.

@lmalina can you check you're ok with how the doc looks now? Steps to get this version of the docs:

- Checkout this branch locally
- run `pip install ".[all]"
- build docs with `python -m sphinx -b html doc ./doc_build -d ./doc_build`
- open the newly created `doc_build` folder, then open `index.html` with your web browser

2020-09-25 19:36 UTC, fsoubelet commented
I'm also including a quick fix in 2555247 for the type hint of `significant_digits`'s return, which was off by one element.

2020-09-26 09:30 UTC, fsoubelet commented
Interestingly the build badge takes the name of the workflow it reports from, so for now on this branch this is `Cron Testing`. I could change the name to `CI Build` or something so that it looks a bit better on the README maybe.

@lmalina @JoschD ?

2020-09-30 08:58 UTC, lmalina requested changes
nice, just few things to be changed ;-)

2020-09-30 08:58 UTC, lmalina commented on tfs/collection.py
> +        and `getbetax.tfs` with BETX and BETY columns respectively:
Put a real file names we use, for example, beta_phase_x.tfs and beta_phase_y.tfs

2020-09-30 08:58 UTC, lmalina commented on tfs/collection.py
> +            beta = Tfs("getbeta{}.tfs")  # A TFS attribute
same here

2020-09-30 08:58 UTC, lmalina commented on tfs/collection.py
> +         # Get the BETX / BETY column from "getbetax.tfs":
same here

2020-09-30 08:58 UTC, lmalina commented on tfs/collection.py
> +         # Get the BETY column from "getbetay.tfs":
and same here

2020-09-30 08:58 UTC, lmalina commented on tfs/handler.py
> +    thus the suspicious identifier does not come from `MAD-X`.
Is this really needed? It duplicates the code

2020-09-30 08:58 UTC, lmalina commented on tfs/tools.py
> +) -> Tuple[Union[str, float], Union[str, float]]:
```Union[Tuple[str, str], Tuple[float,float]]``` , as we do not allow mixed types

2020-09-30 11:45 UTC, fsoubelet commented
All resolved in fd4a0a3. I also added a README file to the workflows directory so it's very clear which one does what.

@lmalina do we want this to be a new pre-minor version (`2.0.1`)? That would be an additional commit.

2020-09-30 11:55 UTC, lmalina commented
> All resolved in [fd4a0a3](https://github.com/pylhc/tfs/commit/fd4a0a348832f92ab4f2edbbe0953b54f367c0e6). I also added a README file to the workflows directory so it's very clear which one does what.
> 
> @lmalina do we want this to be a new pre-minor version (`2.0.1`)? That would be an additional commit.

Yes, the absence of warning on MADX string column types is important to be released.

2020-09-30 11:56 UTC, lmalina approved these changes

2020-09-30 12:10 UTC, merged